// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bywkzdjxzdhwzupfuxxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5d2t6ZGp4emRod3p1cGZ1eHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjE0ODYsImV4cCI6MjA2MDA5NzQ4Nn0.1oBUkIX50rJcgTQ7F2vsCeYuu4cy_6W_QPr6uTq1c68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);